### PR TITLE
improvement: Sort guides by order field in DocSidebar

### PR DESCRIPTION
**Pull request by mbuhot**
This PR changes the `guides_by_categoryand_library` function to order the results by the top level `@start_guides` categories, then by `library.order`, then by `guide.order`.

### CODE REVIEW

**Comment by mbuhot** [comment]
Before this one goes live, the `order` field for the Ash tutorials might need to be updated.
It looks like it's in reverse order right now:

category|library_order|display_name|guide_order|name
---------|------------|-------------|------------|-------
Tutorials|0|Ash|30|Extending Resources
Tutorials|0|Ash|31|Get Started
Tutorials|0|Ash|32|Philosophy
Tutorials|0|Ash|33|Why Ash

**Comment by zachdaniel** [comment]
So right now it gets the order based on their position in the file system when it reads them, which is just alphabetical as far as I can tell. What we'd need to do is prefix them with an integer or something, and then sort them by that, and then strip the integer?

**Comment by zachdaniel** [comment]
Or *maybe* we do it this way to get the best of both worlds (not being able to accidentally leave out a guide in an explicit list) is we provide an option like `guide_order: %{"category" => ["foo", "bar"]}` and either 1. it places anything missing at the end of the explicitly ordered guides or 2. it raises an error if you've omitted a guide from your ordering (on a category by category basis). Thoughts?

**Comment by mbuhot** [comment]
I like the idea of each library supplying a `guide_order` with unspecified guides appearing at the end 👍 
Feels consistent with the existing usage of `partially_alphabetically_sort` where the explicitly ordered first and last items are supplied, and everything else is sorted.

**Comment by zachdaniel** [comment]
Alright, this feature now exists in spark, and the next release of Ash leverages it to order guides.

**Pull request merged**
